from __future__ import annotations

import asyncio
import os
from pathlib import Path

import asyncpg


BOOTSTRAP = r'''
CREATE SCHEMA aios;

CREATE TABLE aios.pipeline_job (
    job_id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    job_type text NOT NULL,
    payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    status text NOT NULL DEFAULT 'queued'
);

CREATE TABLE aios.world (
    world_id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    world_key text UNIQUE
);

CREATE TABLE aios.character_identity (
    character_id text PRIMARY KEY
);

CREATE TABLE aios.character_instance (
    instance_id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    character_id text NOT NULL REFERENCES aios.character_identity(character_id),
    world_id uuid NOT NULL REFERENCES aios.world(world_id),
    current_world_id uuid REFERENCES aios.world(world_id),
    parent_instance_id uuid REFERENCES aios.character_instance(instance_id)
);

CREATE TABLE aios.ingest_event (
    event_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    superseded_at timestamptz
);

CREATE TABLE aios.dag_node (
    node_id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    event_id bigint REFERENCES aios.ingest_event(event_id)
);

CREATE TABLE aios.claim_candidate (
    claim_id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    raw_text text NOT NULL
);

CREATE TABLE aios.claim_context_resolution (
    claim_id uuid PRIMARY KEY REFERENCES aios.claim_candidate(claim_id) ON DELETE CASCADE,
    epistemic_scope text NOT NULL DEFAULT 'source',
    confidence double precision NOT NULL DEFAULT 0.0,
    resolver_version text NOT NULL DEFAULT 'fixture'
);

CREATE TABLE aios.claim_semantic_frame (
    frame_id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    claim_id uuid NOT NULL REFERENCES aios.claim_candidate(claim_id) ON DELETE CASCADE,
    subject_text text,
    object_text text,
    resolved_subject text,
    resolved_object text,
    predicate_canonical text,
    resolution_status text,
    discourse_mode text,
    frame_confidence double precision,
    referent_confidence double precision
);

CREATE TABLE aios.claim_semantic_frame_projection (
    claim_id uuid PRIMARY KEY REFERENCES aios.claim_candidate(claim_id) ON DELETE CASCADE,
    primary_frame_id uuid REFERENCES aios.claim_semantic_frame(frame_id)
);

CREATE TABLE aios.proposition (
    proposition_id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    proposition_hash text NOT NULL UNIQUE,
    topic_key text NOT NULL,
    subject_norm text,
    predicate_norm text,
    object_norm text,
    polarity smallint NOT NULL DEFAULT 1 CHECK (polarity IN (-1,1)),
    canonical_text text NOT NULL,
    modality text NOT NULL DEFAULT 'asserted',
    created_at timestamptz NOT NULL DEFAULT now(),
    meta jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE aios.knowledge_acquisition_event (
    acquisition_id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    instance_id uuid NOT NULL REFERENCES aios.character_instance(instance_id) ON DELETE CASCADE,
    proposition_id uuid REFERENCES aios.proposition(proposition_id) ON DELETE CASCADE,
    claim_id uuid REFERENCES aios.claim_candidate(claim_id) ON DELETE CASCADE,
    acquisition_mode text NOT NULL,
    epistemic_status text NOT NULL DEFAULT 'observed',
    confidence double precision,
    source_entity_id uuid,
    dag_node_id uuid REFERENCES aios.dag_node(node_id),
    created_at timestamptz NOT NULL DEFAULT now(),
    processed_at timestamptz,
    meta jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE aios.character_proposition_knowledge (
    instance_id uuid NOT NULL REFERENCES aios.character_instance(instance_id) ON DELETE CASCADE,
    proposition_id uuid NOT NULL REFERENCES aios.proposition(proposition_id) ON DELETE CASCADE,
    epistemic_status text NOT NULL DEFAULT 'observed',
    confidence double precision,
    acquisition_mode text NOT NULL,
    source_entity_id uuid,
    first_node_id uuid REFERENCES aios.dag_node(node_id),
    last_node_id uuid REFERENCES aios.dag_node(node_id),
    first_acquired_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    meta jsonb NOT NULL DEFAULT '{}'::jsonb,
    base_confidence double precision,
    attention_weight double precision,
    trust_weight double precision,
    compatibility_weight double precision,
    retention_weight double precision,
    salience_weight double precision,
    effective_confidence double precision,
    PRIMARY KEY (instance_id, proposition_id)
);

CREATE TABLE aios.semantic_topology_node (
    topology_node_id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    scope_key text NOT NULL,
    scope_kind text NOT NULL,
    node_type text NOT NULL,
    node_key text NOT NULL,
    label text,
    character_id text,
    character_instance_id uuid,
    world_id uuid,
    dag_node_id uuid,
    proposition_id uuid,
    acquisition_id uuid,
    significance double precision NOT NULL DEFAULT 0.5,
    meta jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (scope_key, node_type, node_key)
);

CREATE TABLE aios.semantic_topology_edge (
    edge_id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    scope_key text NOT NULL,
    parent_node_id uuid NOT NULL REFERENCES aios.semantic_topology_node(topology_node_id) ON DELETE CASCADE,
    child_node_id uuid NOT NULL REFERENCES aios.semantic_topology_node(topology_node_id) ON DELETE CASCADE,
    edge_type text NOT NULL,
    significance double precision NOT NULL DEFAULT 0.5,
    acquisition_id uuid,
    meta jsonb NOT NULL DEFAULT '{}'::jsonb,
    UNIQUE (scope_key, parent_node_id, child_node_id, edge_type)
);
'''

MIGRATIONS = [
    'migrations/20260911_zzz_semantic_scope_projection.sql',
    'migrations/20260911_zzzz_01_semantic_atom_admission.sql',
    'migrations/20260911_zzzz_02_character_belief_state.sql',
    'migrations/20260911_zzzz_03_belief_refresh_projection.sql',
    'migrations/20260911_zzzz_04_belief_backfill.sql',
    'migrations/20260911_zzzz_05_belief_rdf_reprojection.sql',
]


async def _add_evidence(conn, *, instance_id, proposition_id, source_key):
    event_id = await conn.fetchval(
        'INSERT INTO aios.ingest_event DEFAULT VALUES RETURNING event_id'
    )
    node_id = await conn.fetchval(
        'INSERT INTO aios.dag_node(event_id) VALUES ($1) RETURNING node_id',
        event_id,
    )
    acquisition_id = await conn.fetchval(
        """
        INSERT INTO aios.knowledge_acquisition_event(
            instance_id, proposition_id, acquisition_mode,
            confidence, dag_node_id, meta
        )
        VALUES ($1,$2,'observed',0.8,$3,jsonb_build_object('source_key',$4::text))
        RETURNING acquisition_id
        """,
        instance_id,
        proposition_id,
        node_id,
        source_key,
    )
    return acquisition_id, node_id


async def main() -> None:
    conn = await asyncpg.connect(os.environ['AIOS_DB_DSN'])
    try:
        await conn.execute(BOOTSTRAP)
        for migration in MIGRATIONS:
            await conn.execute(Path(migration).read_text(encoding='utf-8'))

        checks = {
            'semantic_atom': await conn.fetchval(
                "SELECT to_regclass('aios.semantic_atom') IS NOT NULL"
            ),
            'semantic_evidence_admission': await conn.fetchval(
                "SELECT to_regclass('aios.semantic_evidence_admission') IS NOT NULL"
            ),
            'character_belief_state': await conn.fetchval(
                "SELECT to_regclass('aios.character_belief_state') IS NOT NULL"
            ),
            'active_belief_view': await conn.fetchval(
                "SELECT to_regclass('aios.character_active_proposition_knowledge') IS NOT NULL"
            ),
            'reconcile_function': await conn.fetchval(
                "SELECT to_regprocedure('aios.reconcile_character_belief_atom(uuid,uuid)') IS NOT NULL"
            ),
            'scope_projection_ledger': await conn.fetchval(
                "SELECT to_regclass('aios.semantic_scope_projection_state') IS NOT NULL"
            ),
        }
        missing = [name for name, present in checks.items() if not present]
        if missing:
            raise AssertionError(f'missing belief reconciliation schema objects: {missing}')

        world_id = await conn.fetchval(
            "INSERT INTO aios.world(world_key) VALUES ('fixture') RETURNING world_id"
        )
        await conn.execute(
            "INSERT INTO aios.character_identity(character_id) VALUES ('Bob')"
        )
        instance_id = await conn.fetchval(
            """
            INSERT INTO aios.character_instance(character_id,world_id,current_world_id)
            VALUES ('Bob',$1,$1)
            RETURNING instance_id
            """,
            world_id,
        )

        pos_id = await conn.fetchval(
            """
            INSERT INTO aios.proposition(
                proposition_hash,topic_key,subject_norm,predicate_norm,object_norm,
                polarity,canonical_text
            )
            VALUES ('pos','bob|located_at','bob','located_at','lab',1,'Bob is in the lab')
            RETURNING proposition_id
            """
        )
        neg_id = await conn.fetchval(
            """
            INSERT INTO aios.proposition(
                proposition_hash,topic_key,subject_norm,predicate_norm,object_norm,
                polarity,canonical_text
            )
            VALUES ('neg','bob|located_at','bob','located_at','lab',-1,'Bob is not in the lab')
            RETURNING proposition_id
            """
        )
        pos_atom = await conn.fetchval(
            'SELECT atom_id FROM aios.proposition WHERE proposition_id=$1', pos_id
        )
        neg_atom = await conn.fetchval(
            'SELECT atom_id FROM aios.proposition WHERE proposition_id=$1', neg_id
        )
        assert pos_atom == neg_atom, 'opposite polarities must share one semantic atom'

        _, pos_node = await _add_evidence(
            conn,
            instance_id=instance_id,
            proposition_id=pos_id,
            source_key='sensor:a',
        )
        _, neg_node = await _add_evidence(
            conn,
            instance_id=instance_id,
            proposition_id=neg_id,
            source_key='sensor:b',
        )

        await conn.execute(
            """
            INSERT INTO aios.character_proposition_knowledge(
                instance_id,proposition_id,epistemic_status,confidence,acquisition_mode,
                first_node_id,last_node_id,effective_confidence
            ) VALUES ($1,$2,'observed',0.8,'observed',$3,$3,0.8)
            """,
            instance_id,
            pos_id,
            pos_node,
        )
        await conn.execute(
            """
            INSERT INTO aios.character_proposition_knowledge(
                instance_id,proposition_id,epistemic_status,confidence,acquisition_mode,
                first_node_id,last_node_id,effective_confidence
            ) VALUES ($1,$2,'observed',0.8,'observed',$3,$3,0.8)
            """,
            instance_id,
            neg_id,
            neg_node,
        )

        state = await conn.fetchrow(
            """
            SELECT stance, positive_support, negative_support
            FROM aios.character_belief_state
            WHERE instance_id=$1 AND atom_id=$2
            """,
            instance_id,
            pos_atom,
        )
        assert state is not None
        assert state['stance'] == 'unresolved', dict(state)

        await _add_evidence(
            conn,
            instance_id=instance_id,
            proposition_id=pos_id,
            source_key='sensor:c',
        )
        state = await conn.fetchrow(
            """
            SELECT stance, positive_support, negative_support
            FROM aios.character_belief_state
            WHERE instance_id=$1 AND atom_id=$2
            """,
            instance_id,
            pos_atom,
        )
        assert state['stance'] == 'positive', dict(state)
        assert state['positive_support'] > state['negative_support']

        active = await conn.fetchrow(
            """
            SELECT proposition_id, stance
            FROM aios.character_active_proposition_knowledge
            WHERE instance_id=$1 AND atom_id=$2
            """,
            instance_id,
            pos_atom,
        )
        assert active is not None
        assert active['proposition_id'] == pos_id
        assert active['stance'] == 'positive'

        projection = await conn.fetchrow(
            """
            SELECT dirty_version, projected_version, status
            FROM aios.semantic_scope_projection_state
            WHERE scope_key='char:Bob'
            """
        )
        assert projection is not None
        assert projection['dirty_version'] > projection['projected_version']
        assert projection['status'] == 'dirty'
    finally:
        await conn.close()


if __name__ == '__main__':
    asyncio.run(main())
